// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Blogs.Context;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(BlogContext))]
    partial class BloggingContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.6");

            modelBuilder.Entity("WebApi.Blogs.Domains.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            Url = "https://devblogs.microsoft.com/dotnet"
                        },
                        new
                        {
                            BlogId = 2,
                            Url = "https://mytravelblog.com/"
                        });
                });

            modelBuilder.Entity("WebApi.Blogs.Domains.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BlogId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            BlogId = 1,
                            Content = "Lorem ipsum dolor sit amet",
                            Title = "What's new"
                        },
                        new
                        {
                            PostId = 2,
                            BlogId = 2,
                            Content = "consectetur adipiscing elit",
                            Title = "Around the World in Eighty Days"
                        },
                        new
                        {
                            PostId = 3,
                            BlogId = 2,
                            Content = "sed do eiusmod tempor incididunt",
                            Title = "Glamping *is* the way"
                        },
                        new
                        {
                            PostId = 4,
                            BlogId = 2,
                            Content = "ut labore et dolore magna aliqua",
                            Title = "Travel in the time of pandemic"
                        });
                });

            modelBuilder.Entity("WebApi.Blogs.Domains.Post", b =>
                {
                    b.HasOne("WebApi.Blogs.Domains.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("WebApi.Blogs.Domains.Blog", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
